services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: Password@1
    ports:
      - '1433:1433'
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: 'Y'
    ports:
      - '5341:80'
    volumes:
      - seq-data:/data

volumes:
  redis-data:
  sql-data:
  seq-data:
